### PR TITLE
cameras 

### PR DESCRIPTION
**Pull request by ghost**
i did this in 1 sitting

### CODE REVIEW

**Comment by ghost** [comment]
fcuking conflicst

**Comment by JohnFulpWillard** [comment]
Hell naw smokey forgot to update to master before starting 💀

**Comment by ghost** [comment]
> Hell naw smokey forgot to update to master before starting 💀

my master is fkfking updated & it was uptodate before i started IM going to go bang my head against the wall because i spent my weekend on thsi

**Comment by ghost** [comment]
die ass hole

**Comment by OneAsianTortoise** [comment]
lmao fuckin L

**Pull request closed without merging**
